### ISSUE TITLE
Photos not appearing into the corresponding annex

### ISSUE THREAD

**Issue by adripanico** [PrevasVST/SubstationRISE#14]
![photos](https://cloud.githubusercontent.com/assets/467658/11065847/dce6ced4-87c5-11e5-9319-7caa71229e4d.png)

**Comment by andreykruglyak** [comment]
Project files needed to address this issue.

**Comment by adripanico** [comment]
In order to send you the project files, I've created a new one from the scratch, and this is what I get:

![photos](https://cloud.githubusercontent.com/assets/467658/11067509/2398184a-87cd-11e5-9cff-1b7d05195b46.PNG)

I've test first with a LS project and later with an Assessment project.

I am sending the project files by email (2015-11-10).

If you see the Assesment project, the picture has been added twice and if you add it to the report, two copies are added. If you delete one of them, the other one is also deleted:

![ass](https://cloud.githubusercontent.com/assets/467658/11067698/2cff3bb0-87ce-11e5-96a0-ca1d0edb6e57.PNG)

**Comment by andreykruglyak** [comment]
In version 1.0.0.31:

Allowed printing of bus bar images and system images when the corresponding system has not been assessed.

Fixed scaling of images (max width 415 px) when uploaded in the application. For existing projects, images wider than 415 px have to be re-added.

Added scaling of images (max width 415 px) when importing from tablet app. THIS HAS NOT BEEN TESTED.

**Comment by adripanico** [comment]
With new project it seems to work, but with previously existing projects, the message "Error generating photo appendix. The other documents will still be generated." still appears.

I'm sending the project files (2015-11-16).

**Comment by andreykruglyak** [comment]
A threading issue. Fixed in version 1.1.0.0.
