### ISSUE TITLE
Enumeration in recommendations & loss of added recommendations

### ISSUE THREAD

**Issue by adripanico** [PrevasVST/SubstationRISE#5]
**Technical recommendations**

When pressing on a component, the recommendations appears below.

The first recommendation shows this on the bottom:
![1](https://cloud.githubusercontent.com/assets/467658/10639890/a003280e-7812-11e5-8efb-b7a65630e0a5.PNG)

If then you click the right arrow, it shows this:
![2](https://cloud.githubusercontent.com/assets/467658/10639888/9fa9e2ee-7812-11e5-9494-7523717afc8d.PNG)

And then, if you click the left arrow, instead of 1, it shows:
![3](https://cloud.githubusercontent.com/assets/467658/10639926/cfe56d34-7812-11e5-9171-0c1498b05cab.PNG)

**Comment by andreykruglyak** [comment]
Known bug, already working on it.

Andrey
Sent from my iPhone

On 21 Oct 2015, at 16:43, Ardi Knight <notifications@github.com<mailto:notifications@github.com>> wrote:


** Technical recommendations **

When pressing on a component, the recommendations appears below.

The first recommendation shows this on the bottom:
[1]<https://cloud.githubusercontent.com/assets/467658/10639890/a003280e-7812-11e5-8efb-b7a65630e0a5.PNG>

If then you click the right arrow, it shows this:
[2]<https://cloud.githubusercontent.com/assets/467658/10639888/9fa9e2ee-7812-11e5-9494-7523717afc8d.PNG>

And then, if you click the left arrow, instead of 1, it shows:
[3]<https://cloud.githubusercontent.com/assets/467658/10639926/cfe56d34-7812-11e5-9171-0c1498b05cab.PNG>

**Comment by andreykruglyak** [comment]
Fixed in version 1.0.0.30.

**Comment by adripanico** [comment]
The issue still remains when firstly entering in the step (with no components selected):

1º The first state is as follows
![1](https://cloud.githubusercontent.com/assets/467658/11811869/74dcd796-a338-11e5-9234-5aa9425d07d8.PNG)

2º if you click the right arrow you get this
![2](https://cloud.githubusercontent.com/assets/467658/11811877/7f762838-a338-11e5-9ef1-836c526a2150.PNG)

3º if you click the right arrow again you get this
![3](https://cloud.githubusercontent.com/assets/467658/11811887/852ba578-a338-11e5-8692-c06ecce6e813.PNG)

4º if you go back to the previous step and then go forward again, you get this
![4](https://cloud.githubusercontent.com/assets/467658/11811899/91cf50fe-a338-11e5-8d7f-ea1c1f4102e1.PNG)

Actually, I'm thinking now what is the reason to have all the recommendations shown before select any component, but in any case it is not working properly.

**Comment by adripanico** [comment]
Update: after this, if you don't select any component the it always says "Recommendation 1 of 1". If you click a component it says *No recommendations are available for the current selection*.

All the already added recommendations have been lost.

This persists even after closing the application and editing the project again.

Project files sent on December 15.

**Comment by andreykruglyak** [comment]
Loss of added recommendation is due to corruption of project data. The source of data corruption must be an earlier crash,

Working now on identifying and removing the source of that crash.

**Comment by andreykruglyak** [comment]
Problem with navigation solved in 1.1.0.9.
